### ISSUE TITLE
tox.iniのcommandsで記述している python setup.py test は現在非推奨になっている

### ISSUE THREAD

**Issue by imaxyz** [beproud/bpmailer#14]
現在、tox.iniのcommandsは `python setup.py test` という記述になっています。

現在、この記述方法は非推奨になっていて、将来廃止される予定があるので、別の記述形式に変更した方がよさそうです。

> Warning
> 
> test is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use [tox](https://tox.readthedocs.io/).

機械翻訳
> testは非推奨であり、将来のバージョンで削除される予定です。テストランナーに依存しない一般的なテストエントリポイントを探しているユーザーは、[tox](https://tox.readthedocs.io/)を使用することをお勧めします。

## 関連コメント

https://github.com/beproud/bpmailer/pull/13/files#r823374974

**Comment by kashewnuts** [comment]
テストライブラリにmockが入っているけど、Python3系からは [unitest.mock](https://docs.python.org/ja/3/library/unittest.mock.html) があるので、合わせて対応したいところ。

**Comment by kashewnuts** [comment]
#21 で対応済みのためClose
